# Generated by Django 5.2.7 on 2025-11-05 15:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('conteudo', models.TextField()),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placar_casa', models.PositiveIntegerField(default=0)),
                ('placar_visitante', models.PositiveIntegerField(default=0)),
                ('data_jogo', models.DateTimeField()),
                ('realizado', models.BooleanField(default=False)),
                ('time_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_casa', to='liga.time')),
                ('time_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_visitante', to='liga.time')),
            ],
        ),
    ]
