# Generated by Django 5.2.7 on 2025-11-05 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placar_casa', models.PositiveIntegerField(default=0)),
                ('placar_visitante', models.PositiveIntegerField(default=0)),
                ('data_jogo', models.DateTimeField()),
                ('realizado', models.BooleanField(default=False)),
                ('time_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_casa', to='liga.time')),
                ('time_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_visitante', to='liga.time')),
            ],
        ),
    ]
